ACCESS_TOKEN_TTL_MINUTES = 15
REFRESH_TOKEN_TTL_HOURS = 24
MAX_SESSION_AGE_HOURS = 24

ROLE_ADMIN = "admin"
ROLE_USER = "user"

SUPPORTED_MFA_TYPES = {"totp", "email", "webauthn"}

ACCESS_TOKEN_TYPE = "access"
REFRESH_TOKEN_TYPE = "refresh"
